### ISSUE TITLE
unit tests failing with different chisq

### ISSUE THREAD

**Issue by timothydmorton** [simonsobs/LAT_MFLike#24]
I am testing the new v0.6 version, and getting a test failure with small differences in chisq:
```
============================================================================================================ short test summary info ============================================================================================================
FAILED mflike/tests/test_mflike.py::MFLikeTest::test_cobaya - AssertionError: 2413.3696293249977 != 2412.9275 within 2 places (0.4421293249979499 difference)
FAILED mflike/tests/test_mflike.py::MFLikeTest::test_mflike - AssertionError: 1384.95286887142 != 1384.5669 within 2 places (0.385968871419891 difference)
========================================================================================================= 2 failed in 282.36s (0:04:42) =========================================================================================================
```

**Comment by xgarrido** [comment]
Yes, I'm pretty sure this is due to new `camb` release 1.3.0 https://github.com/cmbant/CAMB/releases/tag/1.3.0 Previous chi square values were computed with older `camb` release. You should update the tabulated values of chi square within your unit tests (we actually should also do the same).

**Comment by timothydmorton** [comment]
I'm happy to submit a PR to update the tests here with a version check of camb.  Would that be welcome?

**Comment by xgarrido** [comment]
I'm going to fix it because I just have found another issue when testing with MacOS. I will fix both of them and will close this issue when everything goes well. Thanks.

**Comment by timothydmorton** [comment]
In case it saves you a few minutes, the numbers I just got are here:
```
if LooseVersion(camb.__version__) < LooseVersion('1.3'):
    chi2s = {"tt": 1384.5669, "te": 1400.2760, "ee": 1428.7597, "tt-te-et-ee": 2412.9275}
else:
    chi2s = {"tt": 1384.8184, "te": 1400.4507, "ee": 1428.8454, "tt-te-et-ee": 2413.10375}
```

**Comment by xgarrido** [comment]
Ok given the values you provide and fixing `gfortran` binary link for MacOS machine, the CI pass again. Thanks for the notification.
