### ISSUE TITLE
unit tests don't generically work

### ISSUE THREAD

**Issue by timothydmorton** [simonsobs/LAT_MFLike#8]
Trying to debug #7; starting by trying to run unit tests.

First, this line:
https://github.com/simonsobs/LAT_MFLike/blob/e83112bf05a006c25cf005796d91b3d180a74126/mflike/tests/test_mflike.py#L4
My understanding is that cobaya looks for and uses a `$COBAYA_MODULES` env var by default, so any unit tests here should probably imitate that.

Second, the [cobaya documentation](https://cobaya.readthedocs.io/en/latest/theory_camb.html) suggests *not* to install camb generically at the environment level, which means this won't generically work:
https://github.com/simonsobs/LAT_MFLike/blob/e83112bf05a006c25cf005796d91b3d180a74126/mflike/tests/test_mflike.py#L42

**Comment by cmbant** [comment]
It's fine to install camb generically, or with `pip install -e` from github. (the docs are probably thinking about using modified custom versions of camb)

**Comment by xgarrido** [comment]
@timothydmorton can we close this issue as well as the other one ?

**Comment by timothydmorton** [comment]
Yup, fine to close!
